<?xml version="1.0" ?>
<robot name="arch_angel" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find yunshen_robot_description)/urdf/common_properties.xacro"/>
  <xacro:include filename="$(find yunshen_robot_description)/urdf/sensors/sick_tim571_laser.urdf.xacro" />
  <xacro:include filename="$(find yunshen_robot_description)/urdf/sensors/imu.urdf.xacro"/>

    <xacro:property name="base_link_length" value="0.648" />
    <xacro:property name="base_link_width" value="0.714"/>
    <xacro:property name="base_link_height" value="0.2"/>
    <xacro:property name="base_link_mass" value="0.3"/>
    <xacro:property name="wheel_track" value="0.53575"/>
    <xacro:property name="wheel_radius" value="0.084"/>
    <xacro:property name="wheel_width" value="0.05"/>
    <xacro:property name="wheel_separation" value="0.53575"/>
    <xacro:property name="wheel_torque"     value="20.0"/>
    <xacro:property name="wheel_velocity"   value="2.0"/>
    <xacro:property name="PI" value="3.1415926" />
  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0.0 0.0 0.010" rpy="0 0 0"/>
  </joint>


  <link name="base_link">
    <visual>
      <origin xyz="0 0 0.0" rpy="0 0 0"/>
      <geometry>
         <box size="${base_link_length} ${base_link_width} ${base_link_height}"/>
      </geometry>
      <material name="light_black"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_link_length} ${base_link_width} ${base_link_height}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="8.2573504e-01"/>
      <inertia ixx="2.2124416e-03" ixy="-1.2294101e-05" ixz="3.4938785e-05"
               iyy="2.1193702e-03" iyz="-5.0120904e-06"
               izz="2.0064271e-03" />
    </inertial>
  </link>

<xacro:imu_sensor name="imu" parent="base_link" update_rate="100.0">
  <origin xyz="0 0 0" rpy="0 ${0} ${0}"/>
</xacro:imu_sensor>
<!--

  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="-0.032 0 0.068" rpy="0 0 0"/>
  </joint>

  <link name="imu_link"/>
-->

<!--  suzhou juse chache: xyz="0.95 0 ${base_link_height/2 + 0.1} -->
<!--  shanghai kiva test car: xyz="0.14 0 ${base_link_height/2 + 0.1} -->
<joint name="lidar_joint" type="fixed">
  <parent link="base_link"/>
  <child link="base_scan"/>
  <origin xyz="2.231 0.0 ${base_link_height/2 + 0.1}" rpy="0 0 0.0"/>
</joint>

<link name="base_scan">
<visual>
    <origin xyz="0 0 0.0" rpy="0 0 0"/>
    <geometry>
    <cylinder radius="0.05" length="0.005"/>
    </geometry>
    <material name="red"/>
</visual>
</link>

<joint name="base_scan_joint" type="fixed">
  <parent link="base_scan"/>
  <child link="laser"/>
  <origin xyz="0.0 0.0 0.0" rpy="0 0 0.0"/>
</joint>

<link name="laser">
<visual>
    <origin xyz="0 0 0.0" rpy="0 0 0"/>
    <geometry>
    <cylinder radius="0.05" length="0.005"/>
    </geometry>
    <material name="red"/>
</visual>
</link>

</robot>
